### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by somghosh** [sephiroth74/android-target-tooltip#12]
I am seeing the following with LeakCanary. Is there a way to avoid this?

05-20 16:41:17.154  27916-28531/com.gmspartnersltd.earthmiles.debug D/LeakCanary﹕ In com.gmspartnersltd.earthmiles.debug:1.6:6.
    * com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubFragment has leaked:
    * GC ROOT static it.sephiroth.android.library.tooltip.TooltipManager.instances
    * references java.util.concurrent.ConcurrentHashMap.table
    * references array java.util.concurrent.ConcurrentHashMap$Node[].[7]
    * references java.util.concurrent.ConcurrentHashMap$Node.val
    * references it.sephiroth.android.library.tooltip.TooltipManager.mActivity
    * references com.gmspartnersltd.earthmiles.views.MainActivity.mFragments
    * references android.app.FragmentManagerImpl.mAdded
    * references java.util.ArrayList.array
    * references array java.lang.Object[].[0]
    * references com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsFragment.mTabsLinearLayout
    * references android.widget.LinearLayout.mParent
    * references com.astuetz.PagerSlidingTabStrip.pager
    * references android.support.v4.view.ViewPager.mAdapter
    * references com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubTabAdapter.mFragments
    * references java.util.ArrayList.array
    * references array java.lang.Object[].[1]
    * leaks com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubFragment instance
    * Reference Key: 1bba5f56-2b65-4036-a117-1677014e0914
    * Device: Genymotion generic Google Nexus 5 - 5.0.0 - API 21 - 1080x1920 vbox86p
    * Android Version: 5.0 API: 21
    * Durations: watch=5019ms, gc=117ms, heap dump=804ms, analysis=3932ms

**Comment by Epsiloni** [comment]
I've fixed this memory leak on my fork here: https://github.com/Epsiloni/android-target-tooltip

I'm not creating a pull request yet since I've diverged from this repository and I'm also supporting only API >= 14.

**Comment by sephiroth74** [comment]
thank you. I'll check it out

**Comment by somghosh** [comment]
Thanks, I will use your fork
