### ISSUE TITLE
Not parse user@example.com like email

### ISSUE THREAD

**Issue by goodibunakov** [sephiroth74/android-target-tooltip#124]
I use text user@example.com. This parsed like link for email app.
May i disable it action?

**Comment by sephiroth74** [comment]
you can create a custom style and specify which links to parse.

`    <style name="ToolTipAltStyle" parent="ToolTipLayoutDefaultStyle">
        <item name="ttlm_padding">16dp</item>
        <item name="ttlm_backgroundColor">#FF9800</item>
        <item name="ttlm_cornerRadius">6dp</item>
        <item name="ttlm_arrowRatio">1.2</item>
        <item name="ttlm_overlayStyle">@style/ToolTipOverlayAltStyle</item>
        <item name="ttlm_animationStyle">@style/ToolTipAltAnimation</item>
        <item name="ttlm_textStyle">@style/ToolTipAltTextStyle</item>
    </style>

    <style name="ToolTipAltTextStyle" parent="ToolTipTextStyle">
        <item name="android:textColor">@android:color/black</item>
        <item name="android:autoLink">web</item>
    </style>`
