### ISSUE TITLE
Failde to resolve library

### ISSUE THREAD

**Issue by owaisnm** [sephiroth74/android-target-tooltip#127]
I am seeing the following when I include this library: 

```
ERROR: Failed to resolve: com.github.sephiroth74:android-target-tooltip:Tag
Show in Project Structure dialog
Affected Modules: mobile
```

I already have:

```
allprojects {
  repositories {
   maven { url "https://jitpack.io" }
  }
}
```

**Comment by sephiroth74** [comment]
That is just a placeholder. You have to actually pick a release or commit. eg:

    implementation 'com.github.sephiroth74:android-target-tooltip:v2.0.4'
