### ISSUE TITLE
NoClassDefFoundError API 10

### ISSUE THREAD

**Issue by suraj-afrogleap** [sephiroth74/android-target-tooltip#27]
From Android Arsenal the minimumSDK is indicated 9. 
http://android-arsenal.com/details/1/1240

For higher versions it works, but for api 10 i get this error. 
java.lang.NoClassDefFoundError: it.sephiroth.android.library.tooltip.Tooltip$TooltipViewImpl$1

**Comment by sephiroth74** [comment]
Minimum supported SDK is 14. I changed the requirement a while ago.
