### ISSUE TITLE
Turn off dot animation?

### ISSUE THREAD

**Issue by MiralDesai** [sephiroth74/android-target-tooltip#32]
Is there a way to turn off the little bubble that animates in the centre of the view that you tapped on?

It's showing behind my view and looks very weird. I would prefer to turn it off, is that possible?

On a side note, without using a custom view, can I change the text colour? Seems like it should be part of the builder but I can't find a method to indicate so.

Thanks.

**Comment by stavv** [comment]
`.withOverlay(false)`
on the builder does the job
