### ISSUE TITLE
onClick in overlay area, event has interrupted

### ISSUE THREAD

**Issue by ms03001620** [sephiroth74/android-target-tooltip#39]
please fix it

**Comment by douglasjunior** [comment]
Same problem here. Can not be click in any button while tooltip are open.

**Comment by sephiroth74** [comment]
check the ClosePolicy: https://github.com/sephiroth74/android-target-tooltip/blob/master/library/src/main/java/it/sephiroth/android/library/tooltip/Tooltip.java#L112

See the usage in the sample app too

**Comment by douglasjunior** [comment]
I want to click outside, close the tooltip and trigger components in the background.

Its possible?

**Comment by sephiroth74** [comment]
yes, it's already possible

**Comment by douglasjunior** [comment]
If `[onTouchEvent](https://github.com/sephiroth74/android-target-tooltip/blob/master/library/src/main/java/it/sephiroth/android/library/tooltip/Tooltip.java#L1278)` returns `true`, the event stops.

**Comment by douglasjunior** [comment]
Got it.
It is NO CONSUME option, right?

**Comment by sephiroth74** [comment]
yes, set consume outside to false
