### ISSUE TITLE
Crash when Tooltip is open while user presses back button

### ISSUE THREAD

**Issue by thomas-se** [sephiroth74/android-target-tooltip#50]
` Activity activity = (Activity) getContext();` causes a crash using the current AppCompat-Lib as a TintContextWrapper is returned. ([Tooltip line 287](https://github.com/sephiroth74/android-target-tooltip/blob/master/library/src/main/java/it/sephiroth/android/library/tooltip/Tooltip.java#L287))

Used following lines to fix:

``` 
Activity activity = null;

for (Context c = getContext(); c != null; ) {
    if (c instanceof Activity) {
        activity = (Activity) c;
        break;
    } else if (c instanceof ContextWrapper) {
        c = ((ContextWrapper) c).getBaseContext();
    } else {
       c = null;
    }
}
```

**Comment by sephiroth74** [comment]
it should be fixed now
